package com.ssafy.backend.Enum;

public enum PushType {
    LOSTDATA,
    REVIEWLIKE, SUBREVIEW,
    FOLLOW,
    CHAT, DM,
    MEETACCESS, MEETREJECT, MEETEVALUATION, MEETCREATED, MEETMODIFIDE, MEETDELETED
}
